---
- hosts: ubuntu16.04
  remote_user: ansible
  become: true

  tasks:
  - name: change download server from main to jaist
    replace:
      dest=/etc/apt/sources.list
      regexp='http://archive\.ubuntu\.com/ubuntu'
      replace="http://ftp.jaist.ac.jp/pub/Linux/ubuntu"

  - name: change download server from any region to jaist
    replace:
      dest=/etc/apt/sources.list
      regexp='http://.+\.archive\.ubuntu\.com/ubuntu'
      replace="http://ftp.jaist.ac.jp/pub/Linux/ubuntu"

  - name: add repository for tilix
    apt_repository:
      repo: 'ppa:webupd8team/terminix'

  - name: run "apt-get update"
    apt:
      update_cache: yes

  - name: upgrade all packages
    apt:
      upgrade: dist

  - name: run "autoremove"
    apt:
      autoremove: yes

  - name: install base packages
    apt:
      name={{ item }}
    with_items:
      - build-essential
      - dconf-cli
      - gparted
      - fcitx
      - fcitx-mozc
      - xsel
      - language-pack-ja

  - name: create locale ja_JP.UTF-8
    locale_gen:
      name: ja_JP.UTF-8

  - name: set default locale to ja_JP.UTF-8
    command: localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"

    #  - name: set locale to ja_JP.UTF-8
    #    command: update-locale LANG=ja_JP.UTF-8
    #    when: ansible_env.LANG | default('') != 'ja_JP.UTF-8'

  - name: set TimeZone to Asia/Tokyo
    timezone:
      name: Asia/Tokyo

